export const colorPalette = {
  pink: { r: 163, g: 0, b: 0 },
  red: { r: 163, g: 41, b: 0 },
  orange: { r: 163, g: 82, b: 1 },
  yellowOrange: { r: 163, g: 122, b: 0 },
  deepYellow: { r: 163, g: 163, b: 0 },
  orangeGreen: { r: 122, g: 163, b: 0 },
  greenYellow: { r: 82, g: 163, b: 0 },
  greenYellowLight: { r: 41, g: 163, b: 0 },
  greenDark: { r: 0, g: 163, b: 0 },
  green: { r: 0, g: 163, b: 41 },
  greenLight: { r: 0, g: 163, b: 82 },
  greenBlue: { r: 0, g: 163, b: 122 },
  greenBlueLight1: { r: 0, g: 163, b: 163 },
  greenBlueLight2: { r: 0, g: 122, b: 163 },
  greenBlueLight3: { r: 0, g: 82, b: 163 },
  greenBlueLight4: { r: 0, g: 62, b: 163 },
  greenBlueLight5: { r: 0, g: 41, b: 163 },
  blueLight1: { r: 51, g: 181, b: 229 },
  blue: { r: 0, g: 0, b: 163 },
  bluePurple: { r: 41, g: 0, b: 163 },
  purple: { r: 82, g: 0, b: 163 },
  purpleLight: { r: 122, g: 0, b: 163 },
  purpleRed: { r: 163, g: 0, b: 163 },
  pinkLight: { r: 163, g: 0, b: 122 },
  salmonPink: { r: 163, g: 0, b: 82 },
  salmonPinkLight: { r: 163, g: 0, b: 41 },
  salmonPinkLight2: { r: 163, g: 0, b: 0 },
  black: { r: 0, g: 0, b: 0 },
  darkGray: { r: 64, g: 64, b: 64 },
};

export const colorOrder = [
  colorPalette.pink,
  colorPalette.red,
  colorPalette.orange,
  colorPalette.yellowOrange,
  colorPalette.deepYellow,
  colorPalette.orangeGreen,
  colorPalette.greenYellow,
  colorPalette.greenYellowLight,
  colorPalette.greenDark,
  colorPalette.green,
  colorPalette.greenLight,
  colorPalette.greenBlue,
  colorPalette.greenBlueLight1,
  colorPalette.greenBlueLight2,
  colorPalette.greenBlueLight3,
  colorPalette.greenBlueLight4,
  colorPalette.greenBlueLight5,
  colorPalette.blue,
  colorPalette.bluePurple,
  colorPalette.purple,
  colorPalette.purpleLight,
  colorPalette.purpleRed,
  colorPalette.pinkLight,
  colorPalette.salmonPink,
  colorPalette.salmonPinkLight,
  colorPalette.salmonPinkLight2,
  colorPalette.black,
  colorPalette.darkGray,
];
