import {KEY_NAME, OTHER_KEY_NAME} from './keyName';

export const BY_SHARE_ALL_GRAPH_TYPE = [
    KEY_NAME.EV,
    KEY_NAME.MV,
    KEY_NAME.SALES,
    KEY_NAME.OP,
    KEY_NAME.OP_PUB,
    KEY_NAME.OP_CNTN,
    KEY_NAME.NP,
    KEY_NAME.NP_CTRL,
    KEY_NAME.DPRCT,
    KEY_NAME.EBITDA,
    KEY_NAME.NP_NCTRL,
    KEY_NAME.ASST,
    KEY_NAME.LBLT,
    KEY_NAME.EQT,
    KEY_NAME.EQT_CTRL,
    KEY_NAME.EQT_NCTRL,
    KEY_NAME.CMM_STC,
    KEY_NAME.CFO,
    KEY_NAME.CFI,
    KEY_NAME.CFF,
    KEY_NAME.CAPEX,
    KEY_NAME.FCF,
    KEY_NAME.I_B_LBLT,
    KEY_NAME.OPM,
    KEY_NAME.NPM,
    KEY_NAME.ROE,
    KEY_NAME.ROA,
    KEY_NAME.LBLT_RATIO,
    KEY_NAME.EQT_RATIO,
    KEY_NAME.PSR,
    KEY_NAME.POR,
    KEY_NAME.EPS,
    KEY_NAME.PER,
    KEY_NAME.BPS,
    KEY_NAME.PBR,
    KEY_NAME.EV_EBITDA,
    KEY_NAME.CASH_DPS,
    KEY_NAME.DVD_YIELD,
    KEY_NAME.DVD_POT_RATIO,
    KEY_NAME.SHARE_NUM
]

export const BY_MRK_ALL_GRAPH_TYPE = [
    OTHER_KEY_NAME.NUM_OF_CP,
    KEY_NAME.MV, 
    KEY_NAME.SALES, 
    KEY_NAME.OP, 
    KEY_NAME.NP_CTRL,
    KEY_NAME.PSR,
    KEY_NAME.POR,
    KEY_NAME.PER,
    KEY_NAME.PBR,
]

export const BY_SHARE_DEFAULT_GRAPH_TYPE = [
    KEY_NAME.MV,
    KEY_NAME.SALES,
    KEY_NAME.OP,
    KEY_NAME.EBITDA,
    KEY_NAME.NP_CTRL,
    KEY_NAME.PSR,
    KEY_NAME.POR,
    KEY_NAME.PER,
    KEY_NAME.PBR,
    KEY_NAME.EV_EBITDA,
    KEY_NAME.CFI,
]

export const MARKET_SUMMARY_DEFAULT_GRAPH_TYPE = [
    OTHER_KEY_NAME.GDP,
    OTHER_KEY_NAME.M2,
    KEY_NAME.MV,
    KEY_NAME.SALES,
    KEY_NAME.OP,
    KEY_NAME.NP_CTRL,
    KEY_NAME.PSR,
    KEY_NAME.POR,
    KEY_NAME.PER,
]

export const BY_MRK_DEFAULT_GRAPH_TYPE = [
    OTHER_KEY_NAME.NUM_OF_CP,
    KEY_NAME.MV,
    KEY_NAME.SALES,
    KEY_NAME.OP,
    KEY_NAME.NP_CTRL,
    KEY_NAME.PSR,
    KEY_NAME.POR,
    KEY_NAME.PER,
    KEY_NAME.PBR,
]

export const COMPARE_GRAPH_TYPE = [
    KEY_NAME.MV,
    KEY_NAME.SALES,
    KEY_NAME.OP,
    KEY_NAME.OPM,
    KEY_NAME.EBITDA,
    KEY_NAME.NP_CTRL,
    KEY_NAME.NPM,
    KEY_NAME.PSR,
    KEY_NAME.POR,
    KEY_NAME.PER,
    KEY_NAME.PBR,
    KEY_NAME.EV_EBITDA,
]

export const GRAPH_LINE_COLOR = [
    '#000000', // black
    '#aa66cc', // secondary
    '#33b5e5', // info
    '#ffbb33', // warning
    '#ff4444', // danger
    '#2BBBAD', // default
    '#00C851', // success
]