import {KEY_NAME, OTHER_KEY_NAME} from './keyName';

export const BY_SHARE_ALL_GRAPH_TYPE = [
    KEY_NAME.MV,
    KEY_NAME.SALES,
    KEY_NAME.SALES_VAR,
    KEY_NAME.OP,
    KEY_NAME.OP_VAR,
    KEY_NAME.OP_PUB,
    KEY_NAME.OP_CNTN,
    KEY_NAME.NP,
    KEY_NAME.NP_CTRL,
    KEY_NAME.NP_VAR,
    KEY_NAME.NP_NCTRL,
    KEY_NAME.ASST,
    KEY_NAME.DBT,
    KEY_NAME.CPTL,
    KEY_NAME.ASST_CTRL,
    KEY_NAME.ASST_NCTRL,
    KEY_NAME.CPTL,
    KEY_NAME.OA_CF,
    KEY_NAME.IA_CF,
    KEY_NAME.FA_CF,
    KEY_NAME.CAPEX,
    KEY_NAME.FCF,
    KEY_NAME.DBT_I,
    KEY_NAME.OPM,
    KEY_NAME.NPM,
    KEY_NAME.ROE,
    KEY_NAME.ROA,
    KEY_NAME.DBT_RATIO,
    KEY_NAME.CPTL_RATIO,
    KEY_NAME.PCR,
    KEY_NAME.PSR,
    KEY_NAME.POR,
    KEY_NAME.EPS,
    KEY_NAME.PER,
    KEY_NAME.BPS,
    KEY_NAME.PBR,
    KEY_NAME.CASH_DPS,
    KEY_NAME.DVD_YIELD,
    KEY_NAME.DVD_RATIO,
    KEY_NAME.SHARE_NUM
]

export const BY_MRK_ALL_GRAPH_TYPE = [
    OTHER_KEY_NAME.NUM_OF_CP,
    KEY_NAME.MV, 
    KEY_NAME.SALES, 
    KEY_NAME.OP, 
    KEY_NAME.NP_CTRL,
    KEY_NAME.PSR,
    KEY_NAME.POR,
    KEY_NAME.PER,
    KEY_NAME.PCR,
    KEY_NAME.PBR,
]

export const BY_SHARE_DEFAULT_GRAPH_TYPE = [
    KEY_NAME.MV,
    KEY_NAME.SALES,
    KEY_NAME.OP,
    KEY_NAME.NP_CTRL,
    KEY_NAME.PSR,
    KEY_NAME.POR,
    KEY_NAME.PER,
    KEY_NAME.PCR,
    KEY_NAME.PBR,
    KEY_NAME.IA_CF,
]

export const BY_MRK_DEFAULT_GRAPH_TYPE = [
    OTHER_KEY_NAME.NUM_OF_CP,
    KEY_NAME.MV,
    KEY_NAME.SALES,
    KEY_NAME.OP,
    KEY_NAME.NP_CTRL,
    KEY_NAME.PSR,
    KEY_NAME.POR,
    KEY_NAME.PER,
    KEY_NAME.PCR,
    KEY_NAME.PBR,
]

export const COMPARE_GRAPH_TYPE = [
    KEY_NAME.MV,
    KEY_NAME.SALES,
    KEY_NAME.OP,
    KEY_NAME.OPM,
    KEY_NAME.NP_CTRL,
    KEY_NAME.NPM,
    KEY_NAME.PSR,
    KEY_NAME.POR,
    KEY_NAME.PER,
    KEY_NAME.PCR,
    KEY_NAME.PBR,
]

export const GRAPH_LINE_COLOR = [
    '#000000', // black
    '#aa66cc', // secondary
    '#33b5e5', // info
    '#ffbb33', // warning
    '#ff4444', // danger
    '#2BBBAD', // default
    '#00C851', // success
]