export const KEY_NAME = {
    PERIOD:"period",
    SHARE_NAME:"shareName",
    SHARE_CODE:"shareCode",
    MARKET_NAME:"marketName",
    MARKET_CODE:"marketCode",
    MV:"mv",
    SALES:"sales",
    SALES_VAR:"salesVar",
    OP:"op",
    OP_VAR:"opVar",
    OP_PUB:"opPub",
    OP_CNTN:"opCntn",
    NP:"np",
    NP_CTRL:"npCtrl",
    NP_VAR:"npVar",
    NP_NCTRL:"npNctrl",
    ASST:"asst",
    DBT:"lblt",
    CPTL:"eqt",
    ASST_CTRL:"eqtCtrl",
    ASST_NCTRL:"eqtNctrl",
    CPTL:"cmmStc",
    OA_CF:"cfo",
    IA_CF:"cfi",
    FA_CF:"cff",
    CAPEX:"CAPEX",
    FCF:"FCF",
    DBT_I:"dbtI",
    OPM:"opm",
    NPM:"npm",
    ROE:"roe",
    ROA:"roa",
    DBT_RATIO:"lbltRatio",
    CPTL_RATIO:"eqtRatio",
    PCR:"pcr",
    PSR:"psr",
    POR:"por",
    EPS:"eps",
    PER:"per",
    BPS:"bps",
    PBR:"pbr",
    CASH_DPS:"cashDps",
    DVD_YIELD:"dvdYield",
    DVD_RATIO:"dvdRatio",
    SHARE_NUM:"shareNum"
 }

 export const OTHER_KEY_NAME = {
   CODE: "code",
   NAME: "name",
   MARKET_TYPE: "marketType",
   PRICE: "price",
   GRAPH:"graph",
   SCORE:"score",
   NUM_OF_CP: "numOfCp",
   TARGET: "target",
   TYPE: "type",
   SPS: "sps",
   OPS: "ops"
 }