export const KEY_NAME = {
    PERIOD:"period",
    SHARE_NAME:"shareName",
    SHARE_CODE:"shareCode",
    MARKET_NAME:"marketName",
    MARKET_CODE:"marketCode",
    EV:"ev",
    MV:"mv",
    SALES:"sales",
    SALES_VAR:"salesVar",
    OP:"op",
    OP_VAR:"opVar",
    OP_PUB:"opPub",
    OP_CNTN:"opCntn",
    DA: "da",
    EBITDA: "ebitda",
    NOPLAT: "noplat",
    NP:"np",
    NP_CTRL:"npCtrl",
    NP_VAR:"npVar",
    NP_NCTRL:"npNctrl",
    ASST:"asst",
    LBLT:"lblt",
    EQT:"eqt",
    EQT_CTRL:"eqtCtrl",
    EQT_NCTRL:"eqtNctrl",
    CMM_STC:"cmmStc",
    CFO:"cfo",
    CFI:"cfi",
    CFF:"cff",
    CAPEX:"CAPEX",
    IC: "ic",
    FCF:"FCF",
    DBT_I:"dbtI",
    OPM:"opm",
    NPM:"npm",
    EPM:"epm",
    ROE:"roe",
    ROA:"roa",
    ROIC: "roic",
    LBLT_RATIO:"lbltRatio",
    EQT_RATIO:"eqtRatio",
    PCR:"pcr",
    PSR:"psr",
    POR:"por",
    EPS:"eps",
    PER:"per",
    BPS:"bps",
    PBR:"pbr",
    'EV/EBITDA': "ev/ebitda",
    CASH_DPS:"cashDps",
    DVD_YIELD:"dvdYield",
    DVD_RATIO:"dvdRatio",
    SHARE_NUM:"shareNum"
 }

 export const OTHER_KEY_NAME = {
   CODE: "code",
   NAME: "name",
   MARKET_TYPE: "marketType",
   PRICE: "price",
   GRAPH:"graph",
   SCORE:"score",
   NUM_OF_CP: "numOfCp",
   TARGET: "target",
   TYPE: "type",
   SPS: "sps",
   OPS: "ops"
 }