export const MSG = {
    BOX_OVER_MODEL: 'The number of model box could not exceed the number of model',
    MIN_BOX_NUM: 'At least, one model box should exist',
    BOX_ALREADY_EXIST: 'Same box already exists',
    SHARE_CODE_ALREADY_EXIST_IN_CP: 'Same share already exists in the compare list',
    SHARE_CODE_ALREADY_EXIST_IN_BM: 'Same share already exists in the bookmark list',
    NAN: 'Not a number',
    ADD_COMPARE_TG: 'Add to compare list success',
    REMOVE_COMPARE_TG: 'Remove from compare list success',
    ADD_BOOKMARK_TG: 'Add to bookmark list success',
    REMOVE_BOOKMARK_TG: 'Remove from bookmark list success',
    NAN: 'Inserted value is not a number',
    VLT_SAVE: 'Valuation data is saved',
    VLT_REMOVE: 'Valuation data is removed',
    SAVE_COMPARE_MRK_LIST: 'Save compare market list success',
    REMOVE_COMPARE_MRK_LIST: 'Remove compare market list success',
    APPLY_COMPARE_MRK_LIST: 'Apply compare market list success',
    LOGIN_SUCCESS: 'login success',
    LOGIN_FAIL: 'login fail',
    NOT_LOGED_IN: 'Please login',
    LOGOUT_SUCCESS: 'logout success',
    AUTH_MISSING: 'Automatically logout, due to authentication missing'
}